services:
  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - /containers/ollama:/root/.ollama
    gpus: all
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    ports:
      - "30001:3001"
    cap_add:
      - SYS_ADMIN
    env_file:
      - stack.env
    volumes:
      - /mnt/main/containers/anythingllm/storage:/app/server/storage
    restart: always
